# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.26
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import to_back.ecotaxa_cli_py
from to_back.ecotaxa_cli_py.models.object_set_revert_to_history_rsp import ObjectSetRevertToHistoryRsp  # noqa: E501
from to_back.ecotaxa_cli_py.rest import ApiException

class TestObjectSetRevertToHistoryRsp(unittest.TestCase):
    """ObjectSetRevertToHistoryRsp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ObjectSetRevertToHistoryRsp
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = to_back.ecotaxa_cli_py.models.object_set_revert_to_history_rsp.ObjectSetRevertToHistoryRsp()  # noqa: E501
        if include_optional :
            return ObjectSetRevertToHistoryRsp(
                last_entries = [{"objid":264409236,"classif_id":82399,"histo_classif_date":"2021-09-21T14:59:01.007110","histo_classif_type":"M","histo_classif_id":56,"histo_classif_qual":"V","histo_classif_who":3876}], 
                classif_info = {"25932":["Oikopleuridae","Appendicularia"]}
            )
        else :
            return ObjectSetRevertToHistoryRsp(
        )

    def testObjectSetRevertToHistoryRsp(self):
        """Test ObjectSetRevertToHistoryRsp"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
