# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.34
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import to_back.ecotaxa_cli_py
from to_back.ecotaxa_cli_py.api.users_api import UsersApi  # noqa: E501
from to_back.ecotaxa_cli_py.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = to_back.ecotaxa_cli_py.api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_activate_user(self):
        """Test case for activate_user

        Activate User  # noqa: E501
        """
        pass

    def test_create_user(self):
        """Test case for create_user

        Create User  # noqa: E501
        """
        pass

    def test_get_admin_users(self):
        """Test case for get_admin_users

        Get Admin Users  # noqa: E501
        """
        pass

    def test_get_current_user_prefs(self):
        """Test case for get_current_user_prefs

        Get Current User Prefs  # noqa: E501
        """
        pass

    def test_get_user(self):
        """Test case for get_user

        Get User  # noqa: E501
        """
        pass

    def test_get_users(self):
        """Test case for get_users

        Get Users  # noqa: E501
        """
        pass

    def test_get_users_admins(self):
        """Test case for get_users_admins

        Get Users Admins  # noqa: E501
        """
        pass

    def test_reset_user_password(self):
        """Test case for reset_user_password

        Reset User Password  # noqa: E501
        """
        pass

    def test_search_organizations(self):
        """Test case for search_organizations

        Search Organizations  # noqa: E501
        """
        pass

    def test_search_user(self):
        """Test case for search_user

        Search User  # noqa: E501
        """
        pass

    def test_set_current_user_prefs(self):
        """Test case for set_current_user_prefs

        Set Current User Prefs  # noqa: E501
        """
        pass

    def test_show_current_user(self):
        """Test case for show_current_user

        Show Current User  # noqa: E501
        """
        pass

    def test_update_user(self):
        """Test case for update_user

        Update User  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
