# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.34
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import to_back.ecotaxa_cli_py
from to_back.ecotaxa_cli_py.models.object_set_query_rsp import ObjectSetQueryRsp  # noqa: E501
from to_back.ecotaxa_cli_py.rest import ApiException

class TestObjectSetQueryRsp(unittest.TestCase):
    """ObjectSetQueryRsp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ObjectSetQueryRsp
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = to_back.ecotaxa_cli_py.models.object_set_query_rsp.ObjectSetQueryRsp()  # noqa: E501
        if include_optional :
            return ObjectSetQueryRsp(
                object_ids = [634509,6234516,976544], 
                acquisition_ids = [23,987,89], 
                sample_ids = [234,194,12], 
                project_ids = [22,43], 
                details = [[7.315666666666667,43.685],[7.315666666666667,43.685],[7.315666666666667,43.685]], 
                total_ids = 1000
            )
        else :
            return ObjectSetQueryRsp(
        )

    def testObjectSetQueryRsp(self):
        """Test ObjectSetQueryRsp"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
