# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.34
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import to_back.ecotaxa_cli_py
from to_back.ecotaxa_cli_py.models.process_model import ProcessModel  # noqa: E501
from to_back.ecotaxa_cli_py.rest import ApiException

class TestProcessModel(unittest.TestCase):
    """ProcessModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ProcessModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = to_back.ecotaxa_cli_py.models.process_model.ProcessModel()  # noqa: E501
        if include_optional :
            return ProcessModel(
                processid = 1000, 
                orig_id = 'zooprocess_045', 
                free_columns = {"software":"zooprocess_pid_to_ecotaxa_7.26_2017/12/19","pressure_gain":"10"}
            )
        else :
            return ProcessModel(
                processid = 1000,
                orig_id = 'zooprocess_045',
        )

    def testProcessModel(self):
        """Test ProcessModel"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
