# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.26
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import to_back.ecotaxa_cli_py
from to_back.ecotaxa_cli_py.models.export_req import ExportReq  # noqa: E501
from to_back.ecotaxa_cli_py.rest import ApiException

class TestExportReq(unittest.TestCase):
    """ExportReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ExportReq
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = to_back.ecotaxa_cli_py.models.export_req.ExportReq()  # noqa: E501
        if include_optional :
            return ExportReq(
                project_id = 1, 
                exp_type = TSV, 
                use_latin1 = False, 
                tsv_entities = 'OPAS', 
                split_by = 'S', 
                coma_as_separator = False, 
                format_dates_times = False, 
                with_images = False, 
                with_internal_ids = False, 
                only_first_image = False, 
                sum_subtotal = 'A', 
                out_to_ftp = False
            )
        else :
            return ExportReq(
                project_id = 1,
                exp_type = TSV,
                tsv_entities = 'OPAS',
                split_by = 'S',
                coma_as_separator = False,
                format_dates_times = False,
                with_images = False,
                with_internal_ids = False,
                only_first_image = False,
                sum_subtotal = 'A',
                out_to_ftp = False,
        )

    def testExportReq(self):
        """Test ExportReq"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
