# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.41
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import to_back.ecotaxa_cli_py
from to_back.ecotaxa_cli_py.models.general_export_req import GeneralExportReq  # noqa: E501
from to_back.ecotaxa_cli_py.rest import ApiException

class TestGeneralExportReq(unittest.TestCase):
    """GeneralExportReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GeneralExportReq
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = to_back.ecotaxa_cli_py.models.general_export_req.GeneralExportReq()  # noqa: E501
        if include_optional :
            return GeneralExportReq(
                collection_id = 1, 
                project_id = 1, 
                split_by = sample, 
                with_images = first, 
                with_internal_ids = False, 
                with_types_row = False, 
                only_annotations = False, 
                out_to_ftp = False
            )
        else :
            return GeneralExportReq(
                project_id = 1,
        )

    def testGeneralExportReq(self):
        """Test GeneralExportReq"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
