# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.26
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import to_back.ecotaxa_cli_py
from to_back.ecotaxa_cli_py.api.object_api import ObjectApi  # noqa: E501
from to_back.ecotaxa_cli_py.rest import ApiException


class TestObjectApi(unittest.TestCase):
    """ObjectApi unit test stubs"""

    def setUp(self):
        self.api = to_back.ecotaxa_cli_py.api.object_api.ObjectApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_object_query(self):
        """Test case for object_query

        Object Query  # noqa: E501
        """
        pass

    def test_object_query_history(self):
        """Test case for object_query_history

        Object Query History  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
