# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.25
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import to_back.ecotaxa_cli_py
from to_back.ecotaxa_cli_py.models.job_model import JobModel  # noqa: E501
from to_back.ecotaxa_cli_py.rest import ApiException

class TestJobModel(unittest.TestCase):
    """JobModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test JobModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = to_back.ecotaxa_cli_py.models.job_model.JobModel()  # noqa: E501
        if include_optional :
            return JobModel(
                params = {"prj_id":1,"req":{"filters":{"taxo":"85067","taxochild":"N"},"dest_prj_id":1,"group_type":"S","limit_type":"P","limit_value":100.0,"do_images":true}}, 
                result = {"rowcount":3}, 
                errors = [], 
                question = {}, 
                reply = {}, 
                inside = {}, 
                id = 47445, 
                owner_id = 1, 
                type = 'Subset', 
                state = 'F', 
                step = 56, 
                progress_pct = 100, 
                progress_msg = 'Done', 
                creation_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                updated_on = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else :
            return JobModel(
                id = 47445,
                owner_id = 1,
                type = 'Subset',
                creation_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_on = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )

    def testJobModel(self):
        """Test JobModel"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
