# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.41
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import to_back.ecotaxa_cli_py
from to_back.ecotaxa_cli_py.models.backup_export_req import BackupExportReq  # noqa: E501
from to_back.ecotaxa_cli_py.rest import ApiException

class TestBackupExportReq(unittest.TestCase):
    """BackupExportReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BackupExportReq
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = to_back.ecotaxa_cli_py.models.backup_export_req.BackupExportReq()  # noqa: E501
        if include_optional :
            return BackupExportReq(
                collection_id = 1, 
                project_id = 1, 
                out_to_ftp = False
            )
        else :
            return BackupExportReq(
                project_id = 1,
        )

    def testBackupExportReq(self):
        """Test BackupExportReq"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
