# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.41
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import to_back.ecotaxa_cli_py
from to_back.ecotaxa_cli_py.models.minimal_collection_bo import MinimalCollectionBO  # noqa: E501
from to_back.ecotaxa_cli_py.rest import ApiException

class TestMinimalCollectionBO(unittest.TestCase):
    """MinimalCollectionBO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test MinimalCollectionBO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = to_back.ecotaxa_cli_py.models.minimal_collection_bo.MinimalCollectionBO()  # noqa: E501
        if include_optional :
            return MinimalCollectionBO(
                id = 56, 
                external_id = '0', 
                title = '0', 
                short_title = '0', 
                provider_user = 56, 
                contact_user = 56, 
                project_ids = [
                    56
                    ]
            )
        else :
            return MinimalCollectionBO(
                id = 56,
                title = '0',
                provider_user = 56,
                project_ids = [
                    56
                    ],
        )

    def testMinimalCollectionBO(self):
        """Test MinimalCollectionBO"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
