# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.34
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import to_back.ecotaxa_cli_py
from to_back.ecotaxa_cli_py.models.darwin_core_export_req import DarwinCoreExportReq  # noqa: E501
from to_back.ecotaxa_cli_py.rest import ApiException

class TestDarwinCoreExportReq(unittest.TestCase):
    """DarwinCoreExportReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test DarwinCoreExportReq
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = to_back.ecotaxa_cli_py.models.darwin_core_export_req.DarwinCoreExportReq()  # noqa: E501
        if include_optional :
            return DarwinCoreExportReq(
                collection_id = 1, 
                dry_run = False, 
                pre_mapping = {"456":956,"2456":213}, 
                include_predicted = False, 
                with_absent = False, 
                with_computations = ["ABO"], 
                formulae = {"subsample_coef":"1/ssm.sub_part","total_water_volume":"sam.tot_vol/1000","individual_volume":"4.0/3.0*math.pi*(math.sqrt(obj.area/math.pi)*ssm.pixel_size)**3"}
            )
        else :
            return DarwinCoreExportReq(
                collection_id = 1,
        )

    def testDarwinCoreExportReq(self):
        """Test DarwinCoreExportReq"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
