# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.30
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import to_back.ecotaxa_cli_py
from to_back.ecotaxa_cli_py.models.import_rsp import ImportRsp  # noqa: E501
from to_back.ecotaxa_cli_py.rest import ApiException

class TestImportRsp(unittest.TestCase):
    """ImportRsp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ImportRsp
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = to_back.ecotaxa_cli_py.models.import_rsp.ImportRsp()  # noqa: E501
        if include_optional :
            return ImportRsp(
                job_id = 1, 
                errors = ["new TSV file(s) are not compliant"]
            )
        else :
            return ImportRsp(
                job_id = 1,
        )

    def testImportRsp(self):
        """Test ImportRsp"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
