# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.27
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import to_back.ecotaxa_cli_py
from to_back.ecotaxa_cli_py.models.project_set_column_stats_model import ProjectSetColumnStatsModel  # noqa: E501
from to_back.ecotaxa_cli_py.rest import ApiException

class TestProjectSetColumnStatsModel(unittest.TestCase):
    """ProjectSetColumnStatsModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ProjectSetColumnStatsModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = to_back.ecotaxa_cli_py.models.project_set_column_stats_model.ProjectSetColumnStatsModel()  # noqa: E501
        if include_optional :
            return ProjectSetColumnStatsModel(
                proj_ids = [
                    56
                    ], 
                total = 56, 
                columns = [
                    '0'
                    ], 
                counts = [
                    56
                    ], 
                variances = [
                    1.337
                    ]
            )
        else :
            return ProjectSetColumnStatsModel(
        )

    def testProjectSetColumnStatsModel(self):
        """Test ProjectSetColumnStatsModel"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
