# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.41
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import to_back.ecotaxa_cli_py
from to_back.ecotaxa_cli_py.api.guests_api import GuestsApi  # noqa: E501
from to_back.ecotaxa_cli_py.rest import ApiException


class TestGuestsApi(unittest.TestCase):
    """GuestsApi unit test stubs"""

    def setUp(self):
        self.api = to_back.ecotaxa_cli_py.api.guests_api.GuestsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_guest(self):
        """Test case for create_guest

        Create Guest  # noqa: E501
        """
        pass

    def test_get_guest(self):
        """Test case for get_guest

        Get Guest  # noqa: E501
        """
        pass

    def test_get_guests(self):
        """Test case for get_guests

        Get Guests  # noqa: E501
        """
        pass

    def test_search_guest(self):
        """Test case for search_guest

        Search Guest  # noqa: E501
        """
        pass

    def test_update_guest(self):
        """Test case for update_guest

        Update Guests  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
