# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.41
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import to_back.ecotaxa_cli_py
from to_back.ecotaxa_cli_py.api.my_files_api import MyFilesApi  # noqa: E501
from to_back.ecotaxa_cli_py.rest import ApiException


class TestMyFilesApi(unittest.TestCase):
    """MyFilesApi unit test stubs"""

    def setUp(self):
        self.api = to_back.ecotaxa_cli_py.api.my_files_api.MyFilesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_user_file(self):
        """Test case for create_user_file

        Create User File  # noqa: E501
        """
        pass

    def test_list_user_files(self):
        """Test case for list_user_files

        List User Files  # noqa: E501
        """
        pass

    def test_move_user_file(self):
        """Test case for move_user_file

        Move User File  # noqa: E501
        """
        pass

    def test_post_user_file(self):
        """Test case for post_user_file

        Put User File  # noqa: E501
        """
        pass

    def test_remove_user_file(self):
        """Test case for remove_user_file

        Remove User File  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
