# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.41
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import to_back.ecotaxa_cli_py
from to_back.ecotaxa_cli_py.api.common_files_api import CommonFilesApi  # noqa: E501
from to_back.ecotaxa_cli_py.rest import ApiException


class TestCommonFilesApi(unittest.TestCase):
    """CommonFilesApi unit test stubs"""

    def setUp(self):
        self.api = to_back.ecotaxa_cli_py.api.common_files_api.CommonFilesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_common_files(self):
        """Test case for list_common_files

        List Common Files  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
