# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.41
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import to_back.ecotaxa_cli_py
from to_back.ecotaxa_cli_py.api.misc_api import MiscApi  # noqa: E501
from to_back.ecotaxa_cli_py.rest import ApiException


class TestMiscApi(unittest.TestCase):
    """MiscApi unit test stubs"""

    def setUp(self):
        self.api = to_back.ecotaxa_cli_py.api.misc_api.MiscApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_do_nothing(self):
        """Test case for do_nothing

        Do Nothing  # noqa: E501
        """
        pass

    def test_query_ml_models(self):
        """Test case for query_ml_models

        Query Ml Models  # noqa: E501
        """
        pass

    def test_system_error(self):
        """Test case for system_error

        System Error  # noqa: E501
        """
        pass

    def test_used_constants(self):
        """Test case for used_constants

        Used Constants  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
