# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.41
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import to_back.ecotaxa_cli_py
from to_back.ecotaxa_cli_py.models.guest_model import GuestModel  # noqa: E501
from to_back.ecotaxa_cli_py.rest import ApiException

class TestGuestModel(unittest.TestCase):
    """GuestModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GuestModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = to_back.ecotaxa_cli_py.models.guest_model.GuestModel()  # noqa: E501
        if include_optional :
            return GuestModel(
                id = 1, 
                email = 'ecotaxa.api.user@gmail.com', 
                name = 'userName', 
                country = 'France', 
                orcid = '0000-0001-2345-6789', 
                organisation = 'Oceanographic Laboratory of Villefranche sur Mer - LOV'
            )
        else :
            return GuestModel(
                id = 1,
                email = 'ecotaxa.api.user@gmail.com',
                name = 'userName',
                organisation = 'Oceanographic Laboratory of Villefranche sur Mer - LOV',
        )

    def testGuestModel(self):
        """Test GuestModel"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
