# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.41
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import to_back.ecotaxa_cli_py
from to_back.ecotaxa_cli_py.api.myfiles_api import MyfilesApi  # noqa: E501
from to_back.ecotaxa_cli_py.rest import ApiException


class TestMyfilesApi(unittest.TestCase):
    """MyfilesApi unit test stubs"""

    def setUp(self):
        self.api = to_back.ecotaxa_cli_py.api.myfiles_api.MyfilesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_my_file(self):
        """Test case for create_my_file

        Create File  # noqa: E501
        """
        pass

    def test_list_my_files(self):
        """Test case for list_my_files

        List My Files  # noqa: E501
        """
        pass

    def test_move_my_file(self):
        """Test case for move_my_file

        Move File  # noqa: E501
        """
        pass

    def test_post_my_file(self):
        """Test case for post_my_file

        Put My File  # noqa: E501
        """
        pass

    def test_remove_my_file(self):
        """Test case for remove_my_file

        Remove File  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
