# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.30
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import to_back.ecotaxa_cli_py
from to_back.ecotaxa_cli_py.models.project_filters_dict import ProjectFiltersDict  # noqa: E501
from to_back.ecotaxa_cli_py.rest import ApiException

class TestProjectFiltersDict(unittest.TestCase):
    """ProjectFiltersDict unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ProjectFiltersDict
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = to_back.ecotaxa_cli_py.models.project_filters_dict.ProjectFiltersDict()  # noqa: E501
        if include_optional :
            return ProjectFiltersDict(
                taxo = '0', 
                taxochild = '0', 
                statusfilter = '0', 
                map_n = '0', 
                map_w = '0', 
                map_e = '0', 
                map_s = '0', 
                depthmin = '0', 
                depthmax = '0', 
                samples = '0', 
                instrum = '0', 
                daytime = '0', 
                month = '0', 
                fromdate = '0', 
                todate = '0', 
                fromtime = '0', 
                totime = '0', 
                inverttime = '0', 
                validfromdate = '0', 
                validtodate = '0', 
                freenum = '0', 
                freenumst = '0', 
                freenumend = '0', 
                freetxt = '0', 
                freetxtval = '0', 
                filt_annot = '0', 
                filt_last_annot = '0'
            )
        else :
            return ProjectFiltersDict(
        )

    def testProjectFiltersDict(self):
        """Test ProjectFiltersDict"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
