# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.41
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import to_back.ecotaxa_cli_py
from to_back.ecotaxa_cli_py.models.classify_auto_req_mult import ClassifyAutoReqMult  # noqa: E501
from to_back.ecotaxa_cli_py.rest import ApiException

class TestClassifyAutoReqMult(unittest.TestCase):
    """ClassifyAutoReqMult unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ClassifyAutoReqMult
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = to_back.ecotaxa_cli_py.models.classify_auto_req_mult.ClassifyAutoReqMult()  # noqa: E501
        if include_optional :
            return ClassifyAutoReqMult(
                target_ids = [
                    56
                    ], 
                classifications = [
                    [
                        56
                        ]
                    ], 
                scores = [
                    [
                        1.337
                        ]
                    ], 
                keep_log = True
            )
        else :
            return ClassifyAutoReqMult(
                target_ids = [
                    56
                    ],
                classifications = [
                    [
                        56
                        ]
                    ],
                scores = [
                    [
                        1.337
                        ]
                    ],
                keep_log = True,
        )

    def testClassifyAutoReqMult(self):
        """Test ClassifyAutoReqMult"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
