# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.27
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import to_back.ecotaxa_cli_py
from to_back.ecotaxa_cli_py.models.taxon_central import TaxonCentral  # noqa: E501
from to_back.ecotaxa_cli_py.rest import ApiException

class TestTaxonCentral(unittest.TestCase):
    """TaxonCentral unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TaxonCentral
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = to_back.ecotaxa_cli_py.models.taxon_central.TaxonCentral()  # noqa: E501
        if include_optional :
            return TaxonCentral(
                id = 12876, 
                parent_id = 11509, 
                name = 'Echinodermata X', 
                id_source = '70372', 
                taxotype = 'P', 
                display_name = 'Echinodermata X', 
                lastupdate_datetime = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                id_instance = 1, 
                taxostatus = 'A', 
                rename_to = 56, 
                source_url = 'http://www.google.fr/', 
                source_desc = '0', 
                creator_email = 'creator.user@emaim.com', 
                creation_datetime = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                nbrobj = 5800, 
                nbrobjcum = 54800
            )
        else :
            return TaxonCentral(
                id = 12876,
                name = 'Echinodermata X',
                taxotype = 'P',
                taxostatus = 'A',
        )

    def testTaxonCentral(self):
        """Test TaxonCentral"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
