# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.25
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import to_back.ecotaxa_cli_py
from to_back.ecotaxa_cli_py.models.historical_classification import HistoricalClassification  # noqa: E501
from to_back.ecotaxa_cli_py.rest import ApiException

class TestHistoricalClassification(unittest.TestCase):
    """HistoricalClassification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test HistoricalClassification
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = to_back.ecotaxa_cli_py.models.historical_classification.HistoricalClassification()  # noqa: E501
        if include_optional :
            return HistoricalClassification(
                objid = 264409236, 
                classif_id = 82399, 
                classif_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                classif_who = 56, 
                classif_type = 'A', 
                classif_qual = 'P', 
                classif_score = 0.085, 
                user_name = '0', 
                taxon_name = 'Penilia avirostris'
            )
        else :
            return HistoricalClassification(
        )

    def testHistoricalClassification(self):
        """Test HistoricalClassification"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
