# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.26
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import to_back.ecotaxa_cli_py
from to_back.ecotaxa_cli_py.models.import_req import ImportReq  # noqa: E501
from to_back.ecotaxa_cli_py.rest import ApiException

class TestImportReq(unittest.TestCase):
    """ImportReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ImportReq
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = to_back.ecotaxa_cli_py.models.import_req.ImportReq()  # noqa: E501
        if include_optional :
            return ImportReq(
                source_path = '/import_test.zip', 
                taxo_mappings = {"23444":76543}, 
                skip_loaded_files = False, 
                skip_existing_objects = False, 
                update_mode = '0'
            )
        else :
            return ImportReq(
                source_path = '/import_test.zip',
        )

    def testImportReq(self):
        """Test ImportReq"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
