# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.41
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import to_back.ecotaxa_cli_py
from to_back.ecotaxa_cli_py.api.organizations_api import OrganizationsApi  # noqa: E501
from to_back.ecotaxa_cli_py.rest import ApiException


class TestOrganizationsApi(unittest.TestCase):
    """OrganizationsApi unit test stubs"""

    def setUp(self):
        self.api = to_back.ecotaxa_cli_py.api.organizations_api.OrganizationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_organization(self):
        """Test case for create_organization

        Create Organization  # noqa: E501
        """
        pass

    def test_get_organizations(self):
        """Test case for get_organizations

        Get Organizations  # noqa: E501
        """
        pass

    def test_search_organizations(self):
        """Test case for search_organizations

        Search Organizations  # noqa: E501
        """
        pass

    def test_update_organization(self):
        """Test case for update_organization

        Update Organization  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
